- src/functions_framework/cli.py
- tests/test_cli.py
> Fix --signature-type option

- CHANGELOG.md
- src/functions_framework/cli.py
- tests/test_cli.py
> Add support for --dry-run flag

- CHANGELOG.md
- README.md
- setup.py
> Version 1.2.0

- CHANGELOG.md
- setup.py
- src/functions_framework/__main__.py
- src/functions_framework/_cli.py
- tests/test_cli.py
> Add main file

- CHANGELOG.md
- src/functions_framework/__init__.py
- tests/test_functions.py
> Adjust path handling for robots.txt and favicon.ico

- CHANGELOG.md
- README.md
- setup.py
- Add support for running `python -m functions_framework` (#31)
- Move `functions_framework.cli.cli` to `functions_framework._cli._cli`
- Adjust path handling for robots.txt and favicon.ico (#33)
> Version 1.3.0

- CHANGELOG.md
- src/functions_framework/__init__.py
- tests/test_functions.py
- tests/test_functions/module_is_correct/main.py
> Load the source file into the correct module name

- examples/cloud_run_event/Dockerfile
Looks like this sample is broken due to an _ instead of - in the arg.
> Broken sample. It's a dash, not an underscore to specify the sig type.

- CHANGELOG.md
- README.md
- setup.py
> Version 1.4.4

- CHANGELOG.md
- src/functions_framework/__init__.py
- tests/test_functions.py
- tests/test_functions/returns_none/main.py
Cherry-picks from https://github.com/GoogleCloudPlatform/functions-framework-python/tree/version-1.x-dev
> Updates from v1.5.0 and v1.6.0

- .github/workflows/conformance.yml
- .github/workflows/lint.yml
- .github/workflows/unit.yml
- CHANGELOG.md
- setup.py
- tox.ini
~(Draft until the Windows environment is available)~
> Support Python 3.9

- setup.py
> Restrict watchdog dependency

- README.md
> Sample output is not consistent with command (debug on vs. off)

- examples/skaffold/README.md
- examples/skaffold/k8s/goodbye.yaml
- examples/skaffold/k8s/hello.yaml
- examples/skaffold/k8s/ingress.yaml
- examples/skaffold/main.py
- examples/skaffold/requirements.txt
- examples/skaffold/skaffold.yaml
> Add example of developing multiple functions locally

- CHANGELOG.md
- README.md
- setup.py
> Version 2.1.2

- src/functions_framework/_http/gunicorn.py
- tests/test_http.py
> Change gunicorn loglevel to error

- CHANGELOG.md
- README.md
- setup.py
> Version 2.1.3

- .gitignore
- src/functions_framework/__init__.py
- src/functions_framework/event_conversion.py
- tests/test_convert.py
- tests/test_functions.py
- tests/test_functions/cloudevents/empty_data.py
- tests/test_functions/cloudevents/main.py
This commit adds logic to convert cloud event request to background events for functions that have the `event` signature type.
> convert cloud events to background events

- README.md
https://github.com/GoogleCloudPlatform/functions-framework-python/issues/23#issuecomment-833140050
> docs: add quickstart for Pub/Sub emulator

- setup.py
> Relax constraint to flask<3.0 and click<9.0

- README.md
Reduce redundancy in quickstart examples.
> docs: update README to use declarative function signatures

- .github/workflows/buildpack-integration-test.yml
- tests/conformance/prerun.sh
See [functions-framework-conformance builidpack integration workflow PR](https://github.com/GoogleCloudPlatform/functions-framework-conformance/pull/99) for more information.
> chore: add GCF buildpack integration test Workflow

- src/functions_framework/_function_registry.py
- tests/conformance/requirements.txt
- tests/test_functions.py
Replaces https://github.com/GoogleCloudPlatform/functions-framework-python/pull/158 since that PR is outdated.
Tested:
```
python -m tox -e py38-ubuntu-latest 
python -m tox -e lint
.tox/lint/bin/black tests
```
> feat: Add more details to MissingTargetException error

- .github/workflows/conformance.yml
> Update the name of python matrix to be consistent with other repos

- .github/workflows/conformance.yml
- python matrix updates
Update the python matrix in the CI workflows to include the new supported runtimes.
Auto-generated by https://github.com/chizhg/serverless-runtimes-automation/actions/runs/4595514229
> [Automation] Update python matrix

- .github/workflows/scorecard.yml
> chre: Update scorecard.yml with missing endpoint

- .github/workflows/conformance.yml
- .github/workflows/unit.yml
- python matrix updates
Update the python matrix in the CI workflows to include the new supported runtimes.
Auto-generated by https://github.com/chizhg/serverless-runtimes-automation/actions/runs/6665842131
> chore: [Automation] Update python matrix

- .github/workflows/scorecard.yml
needed for security scorecard now, e.g.: https://github.com/GoogleCloudPlatform/functions-framework-python/actions/runs/9118440528
> fix: update scorecard.yml

- .github/workflows/scorecard.yml
> fix: add www.bestpractices.dev:443 to scorecard

- setup.py
> fix: upgrade gunicorn to 22 to fix CVE-2024-1135

- .github/blunderbuss.yml
> chore: remove all assignees from blunderbuss.yml

- setup.py
> fix: Update minimum required version of Flask to 2.0
