GoogleCloudPlatform/functions-framework-python

- setup.py
This is a possible fix for issue #6. Adding watchdog as a dependency would make sure that, when functions-framework is run in DEBUG mode, modifications to files are reloaded.
Fixes #6.
> Make sure that modified files are automatically reloaded.

- README.md
As pointed out in #5 and #6 the debug flag is really helpfull while developing and testing cloud functions so I propose to add it to the official README.md documentation.
Fixes #5.
> Adding `debug` parameter to the README.md documentation.

- setup.py
Previously this would include the next major releases of flask/click.
> Fix typo in install_requires

- CHANGELOG.md
- README.md
- setup.py
> Version 1.0.1

- CHANGELOG.md
- README.md
- src/functions_framework/cli.py
I.e. instead of `--debug TRUE` or `--debug=True`, users can just specify `--debug`.
> Make '--debug' a flag instead of a boolean option

- CHANGELOG.md
- README.md
- setup.py
- src/functions_framework/cli.py
- tests/test_cli.py
> add --host command line argument

- tests/test_cli.py
Looks like the latest version of `click` changes how these error messages are formatted.
> Fix formatting in tests

- .gitignore
- CHANGELOG.md
- README.md
- examples/cloud_run_event/Dockerfile
- examples/cloud_run_http/Dockerfile
- setup.py
- src/functions_framework/__main__.py
- src/functions_framework/_cli.py
- src/functions_framework/_http.py
- tests/test_cli.py
- tests/test_functions.py
- tests/test_http.py
- tests/test_main.py
- tox.ini
Also adds additional test coverage.
> Use Gunicorn for production server

- CHANGELOG.md
- src/functions_framework/_http/__init__.py
- src/functions_framework/_http/flask.py
- src/functions_framework/_http/gunicorn.py
- tests/test_http.py
> Fix handling of debug flag when gunicorn is not present

- setup.py
- tests/test_samples.py
- tox.ini
Integration test for one of the sample projects.
> Test Sample projects

- CHANGELOG.md
- src/functions_framework/__init__.py
- tests/test_functions/module_is_correct/main.py
This improves compatibility with some third-party packages (e.g. `google-python-cloud-debugger`, `numba`) who may want to do introspection of the function.
> Improve module loading

- src/functions_framework/__init__.py
> Read request data after request to prevent connection error

- README.md
- examples/cloud_run_http/Dockerfile
- examples/cloud_run_http/README.md
* Fix the inline example in the `cloud-run-http`
* Add a link to this sample Dockerfile in the main README
> Improve documentation around Dockerfiles

- CHANGELOG.md
- src/functions_framework/__init__.py
- tests/test_functions.py
- tests/test_functions/flask_current_app/main.py
> Execute the source module w/in the app context

- CHANGELOG.md
- README.md
- setup.py
> Version 1.6.0

- README.md
Uses GH actions badge instead of Travis badge.
Travis has not run for 7 months, so it's not the current state of the repo.
---
> docs: github actions badge

- README.md
- Adds GCP buildpack instructions. Fixes https://github.com/GoogleCloudPlatform/functions-framework-python/issues/90
- Formats doc so we don't have many H1 titles, rather H2s.
> docs: format and add buildpack instructions

- src/functions_framework/__init__.py
As-is, this raises an `AttributeError` followed by a "while handling this exception, another exception occurred", followed by the `MissingTargetException`.
It's confusing to include the `AttributeError` in this traceback, so instead we can just test for the attribute and raise the exception if it's missing.
**Before:**
```
$ functions-framework --target test
Traceback (most recent call last):
File "~/googlecloudplatform/functions-framework-python/src/functions_framework/__init__.py", line 251, in create_app
function = getattr(source_module, target)
AttributeError: module 'main' has no attribute 'test'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "~/.pyenv/versions/3.8.2/bin/ff", line 33, in <module> …
```
> Fix how Missingtargetexception raise

- README.md
- src/functions_framework/__init__.py
- tests/test_functions.py
- tests/test_functions/errorhandler/main.py
> Add global errorhandler

- README.md
- setup.py
> Add language-specific alias

- .github/workflows/conformance.yml
- tests/conformance/main.py
> Add conformance tests

- README.md
I've been using this Functions Framework library, which has been great for developing and debugging, and noticed the --help text lists `--dry-run` as a command-line option though it is not documented in the README.
Support for the dry-run flag was added in version 1.1.1 (as noted in the changelog), and it may also be helpful to have it added alongside the other command-line options in the main documentation so that more users can be aware of this functionality!
> Add dry-run command-line flag to README.md

- conftest.py
- src/functions_framework/__init__.py
- tests/test_functions.py
- tests/test_functions/http_check_severity/main.py
- tox.ini
> Add backwards-compatible logging for GCF Python 3.7

- src/functions_framework/__init__.py
Adds the equivalent of this: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/src/logger.ts#L25
> Add crash header to 500 responses

- .github/workflows/conformance.yml
Also use Go 1.15. Go is only used to build the conformance test client.
> Upgrade conformance test version to v0.3.9

- .github/workflows/conformance.yml
This commit updates the functions-framework-conformance action to v0.3.10 and enabled `validateMapping` option to validate CloudEvent => LegacyEvent conversion.
> enable validateMapping for event conformance tests

- README.md
- To make sure that the commands can be run if copied and pasted, need to reinitialize an environment variable in the third terminal. 
- Add command to install `google-cloud-python`
Confirmed that it works when copied and pasted!
> docs: re-init an env var in the third terminal

- src/functions_framework/__init__.py
- tests/test_functions.py
- tests/test_functions/http_log_exception/main.py
Fixes issues in backwards compatibility for GCF Python 3.7.
> Update GCF Python 3.7 backwards-compatible logging

- .github/workflows/conformance.yml
- .gitignore
- src/functions_framework/event_conversion.py
- tests/test_convert.py
- tests/test_data/firebase-db-cloudevent-output.json
- tests/test_data/firebase-db-legacy-input.json
- tests/test_functions/cloudevents/converted_background_event.py
This commit updates the legacy event to cloud event conversion logic to:
- include the `messageId` and `publishTime` fields in the data payload of Pub/Sub events
- include the location in the source field of firebasedatabase events
fixes #139
> fix: cloudevent conversion conformance tests

- README.md
Documents the base request framework used for this library.
Fixes https://github.com/GoogleCloudPlatform/functions-framework-python/issues/80
R @anniefu
> docs: mention flask as the base framework

- src/functions_framework/__init__.py
- tests/test_cloudevent_functions.py
- tests/test_functions.py
Fixes #136. This allows the `functions_framework.errorhandler` to be called on import outside the context of app creation.
> fix: Add a DummyErrorHandler

- examples/README.md
- examples/docker-compose/Dockerfile
- examples/docker-compose/README.md
- examples/docker-compose/docker-compose.yml
- examples/docker-compose/main.py
- examples/docker-compose/requirements.txt
> docs: Add docker-compose example

- README.md
- examples/cloud_run_event/main.py
> docs: Update pub/sub quickstart to use background event

- src/functions_framework/_function_registry.py
- tests/test_functions.py
- tests/test_functions/relative_imports/main.py
- tests/test_functions/relative_imports/test.py
This PR adds support for importing from submodules relative to the directory where the function is defined.
> fix: Support relative imports for submodules

- .github/release-please.yml
This also handles bumping the version number in `setup.py` so that a separate
PR doesn't need to made.
When the GitHub Release is published by the Release Please app, it will
kick off the "Release to PyPI" Workflow.
> chore: use Release Please app for releases

- src/functions_framework/__init__.py
- tests/test_view_functions.py
To make sure function attributes are copied to `_http_view_func_wrapper`
> fix: Add functools.wraps decorator

- src/functions_framework/event_conversion.py
- tests/test_convert.py
fix: for issue #170 gracefully handle pubsub messages without attributes in them
> fix: for issue #170 gracefully handle pubsub messages without attributes in them

- setup.py
`mkdocs>=1.2.2` [depends on](https://github.com/mkdocs/mkdocs/blob/cdf8a26cafa6af6cc78a45766dfec235bd7286cc/setup.py#L69) `watchdog>=2.0` and the restriction of watchdog dependency for functions-framework-python done in #101 seems to be due [an issue related to watchdog built distributions](https://github.com/gorakhargosh/watchdog/issues/689#issuecomment-748241552) (as explained by @di) which is [now fixed](https://github.com/gorakhargosh/watchdog/pull/807).
I propose to allow for `watchdog>=2.0.0` so that a project can use both `mkdocs>=1.2.2` (or `watchdog>=2.0.0`) and `functions-framework-python>=3.0.0`.
> feat: allow for watchdog>=2.0.0

- .github/workflows/buildpack-integration-test.yml
Whoops, missed a tag swap. Should use the default `builder-tag` value, which will be "latest".
> chore: fix buildpack integration test for python39

- .github/workflows/buildpack-integration-test.yml
Increases the wait time for the runtime container to start from the default 1s to 5s.
This will decrease the flakiness of the tests due to not being able to reach the FF container/server because it hasn't started up fully yet.
> test: increase start delay for buildpack integration test

- .github/workflows/conformance.yml
- .github/workflows/unit.yml
In preparation for adding the python311 runtime to GCF, we should start testing this version.
> test: add python 3.11 to unit and conformance test matrices

- README.md
- src/functions_framework/_cli.py
- tests/test_cli.py
Free the DRY_RUN env var name to be used for other purposes by function authors.
The original intent of the DRY_RUN was to be used at build time for GCF to validate function syntax without starting the server, but this was never implemented. For local testing purposes, simply starting the functions framework server is a better method.
> fix: remove DRY_RUN env var and --dry-run flag

- tests/test_cloud_event_functions.py
- tests/test_functions.py
Update unit tests to reflect changes from our dependencies: https://github.com/pallets/werkzeug/pull/2551
Without proper headers, `werkzeug` lib returns 415 error code instead of 400, which is what we're asserting in tests.
Fixes: https://github.com/GoogleCloudPlatform/functions-framework-python/issues/238
> chore: update unit tests with headers

- .github/workflows/codeql.yml
Action https://app.stepsecurity.io/github/GoogleCloudPlatform/functions-framework-python/actions/runs/5147464729 blocked a needed outbound call. Adding it to allowlist.
> chore: add-endpoint-to-allowlist

- .github/workflows/buildpack-integration-test.yml
- tests/conformance/prerun.sh
> chore: run buildpack integration test on pull request

- .github/workflows/lint.yml
- .github/workflows/unit.yml
Workflows using `on: [push, pull_request]` are being duplicated during pull requests wasting runner resources.
> chore: Fix workflow duplication

- README.md
- setup.py
- src/functions_framework/__init__.py
- tests/test_typing.py
- tox.ini
This adds type annotations for the 2 main decorators of the library.
Closes: https://github.com/GoogleCloudPlatform/functions-framework-python/issues/190
I'm also carrying over a small stub file for the event-based functions, which would be now available for everybody.
> feat: initial typing of the public API

- src/functions_framework/__init__.py
- tests/test_functions.py
fixes #213 
Now, if you introduce a syntax error, you immediately get:
```
* Detected change in '/Users/david/src/opvia/app/scripts_v3/cloud_function/main.py', reloading
* Restarting with watchdog (fsevents)
Traceback (most recent call last):
File "/Users/david/src/opvia/app/.venv/lib/python3.10/site-packages/functions_framework/__init__.py", line 290, in create_app
spec.loader.exec_module(source_module)
File "<frozen importlib._bootstrap_external>", line 879, in exec_module
File "<frozen importlib._bootstrap_external>", line 1017, in get_code
File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/Users/david/src/opvia/app/scripts_v3/cloud_function/main.py", line 11
///
^^
SyntaxError: …
```
> fix: don't exit on reload if there is a syntax error

- setup.py
Remove the upper version bound for Gunicorn to unblock fixes and python 3.11 support
> chore(deps): remove gunicorn version upper bound

- src/functions_framework/__init__.py
- src/functions_framework/_http/gunicorn.py
- src/functions_framework/_typed_event.py
- tests/test_http.py
Previously function framework use 0 timeout which is actually "no timeout" restriction.
This was causing a problem that when user provides a request timeout to Cloud function, process will still continue and consume resources.
In this fix, timeout is enabled; default timeout settings is 5 min, same as Cloud run.
To make sure timeout settings will be respected, default settings switched from multi-threads to multi-workers.
However, user is still allowed to  customize workers/threads by assigning env var. But user need to note that timeout won't work when #thread > 1.
>  fix!: avoid long running process when request timeout

- .github/workflows/unit.yml
Workaround for https://github.com/actions/setup-python/issues/696. macos-latest recently was updated to point to macos-14, which does not support Python 3.7, 3.8, 3.9 on ARM.
> chore: Fix unit tests

- setup.py
- src/functions_framework/__init__.py
- src/functions_framework/execution_id.py
- tests/test_execution_id.py
- tests/test_functions/execution_id/main.py
- tests/test_view_functions.py
Enables execution id logging when LOG_EXECUTION_ID env var is set.
> feat: Add execution id

- src/functions_framework/__init__.py
- tests/test_execution_id.py
Allow for explicit disable of execution id logging.
> feat: support disabling execution id logging

- src/functions_framework/_http/gunicorn.py
- tests/test_http.py
> feat: restore gunicorn worker default configs from 3.5.0

- src/functions_framework/_function_registry.py
Removed unused import `re.T` from _function_registry.py
Which was deprecated in [Python 3.13](https://docs.python.org/3/whatsnew/3.13.html#id5)
Which this package doesn't yet explicitly support, but when [creating a PR for this update](https://github.com/glasnt/functions-framework-python/pull/1), I ran into CI issues with [Python 3.13 being too new for setup-python cache](https://github.com/glasnt/functions-framework-python/actions/runs/11376121925/job/31648168174) (which [resolved when removing the harden-runner](https://github.com/glasnt/functions-framework-python/actions/runs/11376283257/job/31648499294), but then there are larger issues [most buildpack-integration tests failing](https://github.com/glasnt/functions-framework-python/actions/runs/11376283279/job/31648505573))
Detected in …
> fix: remove unused import

- examples/cloud_run_cloud_events/requirements.txt
- examples/cloud_run_decorator/requirements.txt
- examples/cloud_run_event/requirements.txt
- examples/cloud_run_http/requirements.txt
- examples/docker-compose/requirements.txt
- examples/skaffold/requirements.txt
- pyproject.toml
Cloudevent SDK implicitly (https://github.com/cloudevents/sdk-python/releases/tag/1.11.1) and then explicitly (https://github.com/cloudevents/sdk-python/releases/tag/1.12.0) dropped support for Python 3.8 and below.
We pin the cloudevent version in functions framework to continue to support python37 and python38 runtimes.
> fix: Pin cloudevent sdk version to support python3.7.

- src/functions_framework/_cli.py
`GATEWAY` appears too plain and may conflict with existing environment variable in action.
> refactor: rename GATEWAY flag to FUNCTION_GATEWAY

- .coveragerc-py37
- src/functions_framework/__init__.py
- src/functions_framework/_cli.py
- src/functions_framework/_function_registry.py
- src/functions_framework/aio/__init__.py
- tests/test_cli.py
- tests/test_decorator_functions.py
- tests/test_function_registry.py
- tests/test_functions.py
- Implement automatic ASGI mode detection for functions decorated with `@aio.http` or `@aio.cloud_event`
- The approach creates a Flask app first, loads the module within its context, then checks if ASGI is needed
- This results in an unused Flask app for ASGI functions, but we accept this memory overhead as a trade-off
- The `--asgi` CLI flag still works and skips the Flask app creation for optimization
- Added `ASGI_FUNCTIONS` set to `_function_registry.py` to track functions that require ASGI
- Updated `@aio.http` and `@aio.cloud_event` decorators to register functions in `ASGI_FUNCTIONS`
- Modified `create_app()` to auto-detect ASGI requirements after module loading:
1. Always creates a Flask app first
2. Loads the user module within Flask app context
3. Checks if target function is …
> feat: auto-detect ASGI mode for @aio decorated functions

- pyproject.toml
This PR removes the `httpx` dependency that was accidentally added in #364 but is never used in the codebase.
While investigating our dependency growth, I discovered that `httpx` was added as a direct dependency but is not imported or used anywhere in the functions-framework codebase. This single dependency brought in 7 additional transitive dependencies.
**Before this PR (28 packages):**
- Direct deps: 10 (including unused httpx)
- Package size: ~29MB
**After this PR (20 packages):**
- Direct deps: 9 (only what we actually use)
- Package size: ~27MB
- **Removes 8 packages**: httpx, anyio, httpcore, h11, certifi, idna, sniffio, typing_extensions
From the last release to current:
- Original: 17 packages
- Added async support: +3 packages (starlette, uvicorn, uvicorn-worker)
- Accidentally …
> fix: remove unused httpx dependency

- .github/workflows/codeql.yml
The CodeQL workflow was failing because the `step-security/harden-runner` was blocking egress traffic to the endpoint used for downloading the CodeQL bundle.
The download from `https://github.com/github/codeql-action/releases` redirects to `release-assets.githubusercontent.com`.
This change adds `release-assets.githubusercontent.com` to the list of allowed endpoints to resolve the `ECONNREFUSED` error and removes previous incorrect attempts.
> fix(ci): Add release-assets.githubusercontent.com to allowed endpoints

- examples/README.md
- examples/cloud_run_async/README.md
- examples/cloud_run_async/main.py
- examples/cloud_run_async/requirements.txt
- examples/cloud_run_async/send_cloud_event.py
- examples/cloud_run_streaming_http/README.md
- examples/cloud_run_streaming_http/main.py
- examples/cloud_run_streaming_http/requirements.txt
Adds two new examples to demonstrate asynchronous and streaming capabilities:
- `cloud_run_async`: Shows how to create basic asynchronous HTTP and CloudEvent functions.
- `cloud_run_streaming_http`: Shows how to create both synchronous and asynchronous streaming HTTP functions.
The examples include instructions for running locally with the `functions-framework` CLI and deploying to Cloud Run with `gcloud`.
> feat: Add async and streaming examples
